# Prometheus configuration for Xillix Real Estate Platform
# Monitoring and alerting configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "xillix-monitor"
    environment: "development"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter (system metrics)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Backend API metrics
  - job_name: "xillix-backend"
    static_configs:
      - targets: ["backend:5000"]
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Frontend metrics (if available)
  - job_name: "xillix-frontend"
    static_configs:
      - targets: ["frontend:3000"]
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Redis metrics
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Nginx metrics
  - job_name: "nginx-exporter"
    static_configs:
      - targets: ["nginx-exporter:9113"]
    scrape_interval: 15s
    metrics_path: /metrics

  # Elasticsearch metrics
  - job_name: "elasticsearch-exporter"
    static_configs:
      - targets: ["elasticsearch-exporter:9114"]
    scrape_interval: 30s
    metrics_path: /metrics

  # Blackbox exporter for endpoint monitoring
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://xillix.co.ke
          - https://xillix.co.ke/api/health
          - https://xillix.co.ke/api/properties
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Custom application metrics
  - job_name: "xillix-custom-metrics"
    static_configs:
      - targets: ["backend:5000"]
    scrape_interval: 30s
    metrics_path: /api/metrics/custom
    scrape_timeout: 10s
# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read configuration
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"
